name: tg_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytest
  - pytest-mock
  - pytest-cov
  - requests
  - biolink-model
  - jsonasobj2
  - linkml_runtime
  - humanize
  - sqlalchemy
  - pymysql
  - neo4j
  - psycopg2
  - pandas
  - openpyxl
  - GEOparse
  - graphene
  - Flask
  - pyyaml
  - cwltool