global:
  qc_mode: true

phenotype:
  hpo:
    download_url_obo: "http://purl.obolibrary.org/obo/hp.obo"
    download_url_owl: "http://purl.obolibrary.org/obo/hp.owl"
    download_url_phenotype_hpoa: "https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2025-05-06/phenotype.hpoa"
    download_url_genes_to_phenotype: "https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2025-05-06/genes_to_phenotype.txt"
    download_url_phenotype_to_genes: "https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2025-05-06/phenotype_to_genes.txt"
    raw_dir: "src/data/publicdata/phenotype_data/raw/"
    metadata_file: "src/data/publicdata/phenotype_data/metadata/hpo_download_metadata.json"
    raw_phenotype_hpoa: "src/data/publicdata/phenotype_data/raw/phenotype.hpoa"
    raw_genes_to_phenotype: "src/data/publicdata/phenotype_data/raw/genes_to_phenotype.txt"
    raw_phenotype_to_genes: "src/data/publicdata/phenotype_data/raw/phenotype_to_genes.txt"
    cleaned_genes_to_phenotype: "src/data/publicdata/phenotype_data/cleaned/genes_to_phenotype.csv"
    cleaned_phenotype_to_genes: "src/data/publicdata/phenotype_data/cleaned/phenotype_to_genes.csv"
    transform_metadata_file: "src/data/publicdata/phenotype_data/metadata/hpo_transform_metadata.json"
