services:
  fastapi-pharos:
    build:
      dockerfile: graphql-container/Dockerfile
      context: ..
    container_name: fastapi-pharos
    ports:
      - "8045:8000"
    environment:
      YAML_FILE: ./src/use_cases/api/pharos_prod_dashboard.yaml
    restart: unless-stopped
    networks:
      - dashboard_network

networks:
  dashboard_network:
    name: shared_dashboard_network
    driver: bridge
