services:
  fastapi-pharos:
    build:
      dockerfile: graphql-container/Dockerfile
      context: ..
    container_name: fastapi-pharos
    ports:
      - "8045:8000"
    environment:
      YAML_FILE: ./src/use_cases/api/pharos_dev_dashboard.yaml
    restart: unless-stopped
