services:
  odin-api:
    build:
      dockerfile: graphql-container/Dockerfile
      context: ..
    container_name: odin-api
    ports:
      - "8045:8000"
    restart: unless-stopped
    networks:
      - dashboard_network

networks:
  dashboard_network:
    name: shared_dashboard_network
    driver: bridge
