services:
  arangodb:
    image: arangodb:latest
    container_name: local_arangodb
    env_file:
      - secrets.env
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    networks:
      - dashboard_network

volumes:
  arangodb_data:
  arangodb_apps:

networks:
  dashboard_network:
    external: true
    name: shared_dashboard_network
