services:
  pounce_dev_arangodb:
    image: arangodb:latest
    container_name: pounce_dev
    env_file:
      - secrets.env
    ports:
      - "8043:8529"
    volumes:
      - pounce_dev_data:/var/lib/arangodb3
      - pounce_dev_apps:/var/lib/arangodb3-apps
    networks:
      - dashboard_network

volumes:
  pounce_dev_data:
  pounce_dev_apps:

networks:
  dashboard_network:
    external: true
    name: shared_dashboard_network
