services:
  pharos_prod_arangodb:
    image: arangodb:latest
    container_name: pharos_prod
    env_file:
      - secrets.env
    ports:
      - "8042:8529"
    volumes:
      - pharos_prod_data:/var/lib/arangodb3
      - pharos_prod_apps:/var/lib/arangodb3-apps
    networks:
      - dashboard_network

volumes:
  pharos_prod_data:
  pharos_prod_apps:

networks:
  dashboard_network:
    external: true
    name: shared_dashboard_network
