services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    env_file:
      - secrets.env
    ports:
      - "8044:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps

volumes:
  arangodb_data:
  arangodb_apps:
