services:
  pounce_prod_arangodb:
    image: arangodb:latest
    container_name: pounce_prod
    env_file:
      - secrets.env
    ports:
      - "8044:8529"
    volumes:
      - pounce_prod_data:/var/lib/arangodb3
      - pounce_prod_apps:/var/lib/arangodb3-apps

volumes:
  pounce_prod_data:
  pounce_prod_apps:
