services:
  pharos_prod_memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: pharos_prod
    ports:
      - "8044:7687"
    command: ["--log-level=TRACE"]
    env_file:
      - secrets.env
    environment:
      - MEMGRAPH_DBMS_MEMORY_HEAP_SIZE=12g
      - MEMGRAPH_DBMS_MEMORY_PAGECACHE_SIZE=9g
    mem_limit: 21g
    volumes:
      - pharos_prod_data:/var/lib/memgraph

  pharos_prod_lab:
    image: memgraph/lab:latest
    container_name: pharos_prod_lab
    ports:
      - "8043:3000"
    depends_on:
      - pharos_prod_memgraph
    env_file:
      - secrets.env
    environment:
      - QUICK_CONNECT_MG_HOST=pharos_prod_memgraph
      - QUICK_CONNECT_MG_PORT=7687

volumes:
  pharos_prod_data: