services:
  pounce_dev_memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: pounce_dev
    ports:
      - "8046:7687"
    command: ["--log-level=TRACE"]
    env_file:
      - secrets.env
    environment:
      - MEMGRAPH_DBMS_MEMORY_HEAP_SIZE=16g
      - MEMGRAPH_DBMS_MEMORY_PAGECACHE_SIZE=32g
    mem_limit: 48g
    volumes:
      - pounce_dev_data:/var/lib/memgraph

  pounce_dev_lab:
    image: memgraph/lab:latest
    container_name: pounce_dev_lab
    ports:
      - "8045:3000"
    depends_on:
      - pounce_dev_memgraph
    env_file:
      - secrets.env
    environment:
      - QUICK_CONNECT_MG_HOST=pounce_dev_memgraph
      - QUICK_CONNECT_MG_PORT=7687

volumes:
  pounce_dev_data: