services:
  pharos_prod_memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: pharos_prod
    ports:
      - "8044:7687"
    command: ["--log-level=TRACE"]
    environment:
      - MEMGRAPH_USER=neo4j
      - MEMGRAPH_PASSWORD=password
    volumes:
      - pharos_prod_data:/var/lib/memgraph

  pharos_prod_lab:
    image: memgraph/lab:latest
    container_name: pharos_prod_lab
    ports:
      - "8043:3000"
    depends_on:
      - pharos_prod_memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=pharos_prod_memgraph
      - QUICK_CONNECT_MG_PORT=7687
      - QUICK_CONNECT_MG_USER=neo4j
      - QUICK_CONNECT_MG_PASSWORD=password

volumes:
  pharos_prod_data: