services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
    environment:
      - MEMGRAPH_USER=neo4j
      - MEMGRAPH_PASSWORD=password
    volumes:
      - memgraph_data:/var/lib/memgraph
      - ./logs:/var/log/memgraph
    command: ["--log-level=TRACE"]

  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
      - QUICK_CONNECT_MG_USER=neo4j
      - QUICK_CONNECT_MG_PASSWORD=password

volumes:
  memgraph_data: