version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./apoc:/plugins
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_memory_heap_initial__size: 4g
      NEO4J_dbms_memory_heap_max__size: 8g
      NEO4J_dbms_memory_pagecache_size: 4g
    networks:
      - neo4j-network

volumes:
  neo4j_data:

networks:
  neo4j-network:
